
export const GET_WORKSPACE = "GET_WORKSPACE";
export const UPDATE_WORKSPACE_PROPERTIES = "UPDATE_WORKSPACE_PROPERTIES";

export const ADD_NEW_PROJECT = "ADD_NEW_PROJECT";
export const UPDATE_LIST_PROJECTS = "UPDATE_LIST_PROJECTS";
export const SHOW_PROJECT = "SHOW_PROJECT";

export const CREATE_NEW_MEMBER = "CREATE_NEW_MEMBER";
//member 
export const GET_LIST_MEMBER_IN_WORKSPACE = "GET_LIST_MEMBER_IN_WORKSPACE";
export const UPDATE_LIST_MEMBER_IN_WORKSPACE = "UPDATE_LIST_MEMBER_IN_WORKSPACE";

export const UPDATE_FILTER_STAFF = "UPDATE_FILTER_STAFF";
