
export const GET_WORKSPACE = "GET_WORKSPACE";
export const UPDATE_WORKSPACE_PROPERTIES = "UPDATE_WORKSPACE_PROPERTIES";

export const ADD_NEW_PROJECT = "ADD_NEW_PROJECT";

export const CREATE_NEW_MEMBER = "CREATE_NEW_MEMBER";