

export const UPDATE_PROJECT_DETAIL = "UPDATE_PROJECT_DETAIL";
export const UPDATE_ITEM_IN_PROJECT = "UPDATE_ITEM_IN_PROJECT";

//mile stone
export const GET_LIST_MILESTONE = "GET_LIST_MILESTONE";
export const CREATE_NEW_MILESTONE = "CREATE_NEW_MILESTONE";

// member
export const UPDATE_MEMBER_IN_PROJECT = "UPDATE_MEMBER_IN_PROJECT";

export const GET_LIST_MEMBER_IN_PROJECT = "GET_LIST_MEMBER_IN_PROJECT";