

export const UPDATE_PROJECT_DETAIL = "UPDATE_PROJECT_DETAIL";
export const UPDATE_ITEM_IN_PROJECT = "UPDATE_ITEM_IN_PROJECT";

//mile stone
export const GET_LIST_MILESTONE = "GET_LIST_MILESTONE";
export const CREATE_NEW_MILESTONE = "CREATE_NEW_MILESTONE";
export const UPDATE_MILESTONE = "UPDATE_MILESTONE";

// member
export const UPDATE_MEMBER_IN_PROJECT = "UPDATE_MEMBER_IN_PROJECT";

export const GET_LIST_MEMBER_IN_PROJECT = "GET_LIST_MEMBER_IN_PROJECT";
export const UPDATE_LIST_MEMBER_IN_PROJECT = "UPDATE_LIST_MEMBER_IN_PROJECT";

export const GET_LIST_TASK_IN_PROJECT = "GET_LIST_TASK_IN_PROJECT";
export const UPDATE_LIST_TASK_IN_PROJECT = "UPDATE_LIST_TASK_IN_PROJECT";

export const CREATE_TASK_IN_PROJECT = "CREATE_TASK_IN_PROJECT";

export const CREATE_SUB_TASK_IN_PROJECT = "CREATE_SUB_TASK_IN_PROJECT";

export const CREATE_NEW_COMMENT = "CREATE_NEW_COMMENT";

export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const GET_LIST_COMMENT = "GET_LIST_COMMENT";

export const UPDATE_FILTER_TASK = "UPDATE_FILTER_TASK";
export const CLEAR_FILTER_TASK = "CLEAR_FILTER_TASK";

export const UPDATE_FILTER_PROJECT = "UPDATE_FILTER_PROJECT";
export const CLEAR_FILTER_PROJECT = "CLEAR_FILTER_PROJECT";